In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
arr_1d=np.array([1,2,3])
arr_1d

array([1, 2, 3])

In [4]:
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
zeros=np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
ones=np.ones([3,3])
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
random_arr=np.random.random([5,4])
random_arr

array([[0.93580566, 0.2905196 , 0.24051869, 0.88383947],
       [0.00655854, 0.42435472, 0.53708787, 0.50778626],
       [0.21633643, 0.11223548, 0.37686443, 0.25131255],
       [0.78138544, 0.98539876, 0.88078563, 0.78478327],
       [0.97188621, 0.39946411, 0.79705794, 0.23703889]])

In [23]:
identity=np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
range_arr=np.arange(0,10,2)
range_arr

array([0, 2, 4, 6, 8])

In [27]:
arr=np.array([[1,2,3],[4,5,6]])
print('Shape:',arr.shape)
print('Size:',arr.size)
print('Data Type:',arr.dtype)
print('Numner of Dimensions:',arr.ndim)

Shape: (2, 3)
Size: 6
Data Type: int32
Numner of Dimensions: 2


In [30]:
arr[0][1] #arr[0,1]

2

In [31]:
arr[1,2]

6

In [34]:
arr[0:2,1:3] #arr[:,1:]

array([[2, 3],
       [5, 6]])

In [39]:
arr1=np.array([2,3,4])
arr2=np.array([6,7,8])
arr1+arr2

array([ 8, 10, 12])

In [40]:
arr1*arr2

array([12, 21, 32])

In [48]:
darr1=np.array([[3,4,5],[4,5,6],[6,7,8]])
darr2=np.array([[1,2,3],[7,8,9],[3,4,5]])
res=np.dot(darr1,darr2)
res

array([[ 46,  58,  70],
       [ 57,  72,  87],
       [ 79, 100, 121]])

In [49]:
darr1@darr2

array([[ 46,  58,  70],
       [ 57,  72,  87],
       [ 79, 100, 121]])

In [51]:
import matplotlib.pyplot as plt

In [52]:
plt.plot(darr1,darr2)
plt.show()

In [53]:
print(np.exp(arr1))
print(np.sqrt(arr1))
print(np.log(arr1))

[ 7.3890561  20.08553692 54.59815003]
[1.41421356 1.73205081 2.        ]
[0.69314718 1.09861229 1.38629436]


In [54]:
print("Sum is:",np.sum(arr1))
print("Mean is:",np.mean(arr1))
print("Standard Deviation is:",np.std(arr1))
print("Max is:",np.max(arr1))
print("Min is:",np.min(arr1))

Sum is: 9
Mean is: 3.0
Standard Deviation is: 0.816496580927726
Max is: 4
Min is: 2


In [56]:
a=np.array([1,2,3])
b=np.array([2,3,4])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [2 3 4]]
[1 2 3 2 3 4]


In [57]:
arr=np.array([1,2,3,4,5,6])
np.array_split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [58]:
arr=np.array([1,2,3,4])
view=arr.view()
view[0]=10
print(arr)
arr=np.array([1,2,3,4])
cp=arr.copy()
cp[0]=100
print(arr)

[10  2  3  4]
[1 2 3 4]


In [60]:
np.save('arr.npy',arr)
loaded_arr=np.load('arr.npy')
print(loaded_arr)

[1 2 3 4]
